### ISSUE TITLE
Notes field does not always show previous version when navigating back in time

### ISSUE THREAD

**Issue by divv** [projectwell8/riskprofileapp#1]
_From @divv on December 6, 2018 21:0_

**To Repro:**

1.  Load a profile
2.  Enter or change the notes for any question and change the scale.
3.  Click 'Save'
4.  Use the Version History links on the right to go back to the previous version

**Expected Behaviour**
The notes field should revert to what it was as at the previous version

**Actual Behaviour**
The Scale field correctly reverts, but the Notes field remains latest.

_Copied from original issue: divv/unboxd_riskeasy#1_

**Comment by divv** [comment]
It actually works if you refresh the page, then the behaviour is as expected.
A workaround could be to force a page refresh or profile reload on save.

**Comment by anhnguyen0110** [comment]
This issue has been addressed on current risk tool app.
